requires 'Catalyst::Runtime', '5.80';
requires 'Catalyst::View::MicroTemplate::DataSection';
requires 'Catalyst::Action::RenderView';
requires 'Catalyst::Plugin::Static::Simple';
requires 'Catalyst::Plugin::Session::Store::FastMmap';
requires 'Catalyst::Plugin::Session::State::Cookie';
requires 'DBI';
requires 'DBD::SQLite';
requires 'Teng::Schema::Loader';
